[workspace]
members = ["mock-lib", "mock-lib-derive", "mock-example-project"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["rzeppa.jakob@gmail.com"]
license = "MIT"
repository = "https://github.com/jakob-rzeppa/rust-helpers-macros"
